apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-ingress
  namespace: webhook
  annotations:
    networking.gke.io/managed-certificates: webhook-certificate
spec:
  ingressClassName: "gce"
  defaultBackend:
    service:
      name: webhook-service
      port:
        number: 80
