apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: webhook
spec:
  selector:
    app: webhook-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
